networks:
  infra-net:
    external: true
  coolify:
    external: true

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    networks:
      - infra-net
      - coolify
    ports:
      - "127.0.0.1:8023:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.mystackmint.com`)"
      - "traefik.http.routers.adminer.entrypoints=https"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.middlewares=authelia@docker"
      - "traefik.docker.network=coolify"
    environment:
      - ADMINER_DESIGN=dracula
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 60s
      timeout: 5s
      retries: 3
