networks:
  infra-net:
    external: true
  coolify:
    external: true

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    networks:
      - infra-net
      - coolify
    ports:
      - "127.0.0.1:8021:61208"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.mystackmint.com`)"
      - "traefik.http.routers.glances.entrypoints=https"
      - "traefik.http.routers.glances.tls=true"
      - "traefik.http.routers.glances.tls.certresolver=letsencrypt"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.routers.glances.middlewares=authelia@docker"
      - "traefik.docker.network=coolify"
    environment:
      - GLANCES_OPT=-w
      - TZ=UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
