http:
  routers:
    jellyfin-http:
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      rule: Host(`jellyfin.mystackmint.com`)
      service: jellyfin
    jellyfin-https:
      entryPoints:
        - https
      rule: Host(`jellyfin.mystackmint.com`)
      service: jellyfin
      tls:
        certresolver: letsencrypt
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: 'http://100.119.69.2:8096'
