networks:
  personal-net:
    external: true
  coolify:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    networks:
      - personal-net
      - coolify
    ports:
      - "127.0.0.1:8008:4533"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.mystackmint.com`)"
      - "traefik.http.routers.navidrome.entrypoints=https"
      - "traefik.http.routers.navidrome.tls=true"
      - "traefik.http.routers.navidrome.tls.certresolver=letsencrypt"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - "traefik.http.routers.navidrome.middlewares=authelia@docker"
      - "traefik.docker.network=coolify"
    user: "1000:1000"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=https://music.mystackmint.com
    volumes:
      - navidrome_data:/data
      - /media/music:/music:ro

volumes:
  navidrome_data:
