server {
    listen 443 ssl;
    server_name mystackmint.com;

    include snippets/ssl.conf;
    include snippets/security-headers.conf;

    location / {
        include snippets/proxy-params.conf;
        proxy_pass http://homepage:80;
    }
}
