server {
    listen 443 ssl;
    server_name photos.mystackmint.com;

    include snippets/ssl.conf;
    include snippets/security-headers.conf;

    client_max_body_size 50G;
    client_body_timeout 600s;

    location / {
        include snippets/authelia-auth.conf;
        include snippets/proxy-params.conf;
        proxy_pass http://immich-server:2283;
    }

    include snippets/authelia-location.conf;
}
