server {
    listen 443 ssl;
    server_name media.mystackmint.com;

    include snippets/ssl.conf;
    include snippets/security-headers.conf;

    location / {
        include snippets/authelia-auth.conf;
        include snippets/proxy-params.conf;
        proxy_pass http://jellyfin:8096;
    }

    include snippets/authelia-location.conf;
}
