server {
    listen 443 ssl;
    server_name cloud.mystackmint.com;

    include snippets/ssl.conf;
    include snippets/security-headers.conf;

    client_max_body_size 10G;
    client_body_timeout 300s;

    location = /.well-known/carddav { return 301 $scheme://$host/remote.php/dav; }
    location = /.well-known/caldav  { return 301 $scheme://$host/remote.php/dav; }

    location / {
        include snippets/authelia-auth.conf;
        include snippets/proxy-params.conf;
        proxy_pass http://nextcloud:80;
    }

    include snippets/authelia-location.conf;
}
