server {
    listen 443 ssl;
    server_name vault.mystackmint.com;

    include snippets/ssl.conf;
    include snippets/security-headers.conf;

    client_max_body_size 128m;

    location / {
        include snippets/authelia-auth.conf;
        include snippets/proxy-params.conf;
        proxy_pass http://vaultwarden:80;
    }

    include snippets/authelia-location.conf;
}
