networks:
  infra-net:
    external: true

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - infra-net
    environment:
      - TZ=UTC
      - DOCKER_API_VERSION=1.41
      - WATCHTOWER_SCHEDULE=0 0 3 * * SUN
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_NO_PULL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
